Catalogue Support
GenerationsMod/Generations-Core pull request #47
Opened 2024-08-14 19:52 UTC by ChaosDogG

Should have Catalogue mod by MrCrayfish use Generation's icon

2024-10-04 03:04 UTC, JT122406 requested changes
These Tags are Datagenned and should be done in code and not manually made jsons

2024-10-04 05:56 UTC, ChaosDogG commented
I see, i will figure out how to fix that in the morning

2024-10-04 05:57 UTC, ChaosDogG commented
Or rather, when i get the chance tomorrow

2024-11-09 20:57 UTC, Dysth commented
checking in on this, can do it ourselves shortly if you need us to since this contains valid bug fixes

2024-11-26 20:41 UTC, ChaosDogG commented
that'd b awesome, thanks!

2024-11-26 20:44 UTC, ChaosDogG commented
i also forgor to add silicon to a tag as well, should b forge:silicon iirc

2026-02-08 16:58 UTC, Dysth commented
This was merged manually a while ago, closing. Thanks again

2026-02-08 16:58 UTC, closed without merging